### ISSUE TITLE
CxFlow does not support OSA Scans

### ISSUE THREAD

**Issue by miguelfreitas93** [checkmarx-ltd/cx-flow#327]
### Description

Right now we cannot trigger OSA scans using CxFlow, which is an issue.
Beside there is some sort of implementation in this line: https://github.com/checkmarx-ltd/cx-flow/blob/a738694c045a0f3677c692949b75f6b503c03047/src/main/java/com/checkmarx/flow/service/SastScanner.java#L385

Looking at SDK, this flag is always false: https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/blob/14b71c09ddad46f7343d7f6e2321ee7252dfbc24/src/main/java/com/checkmarx/sdk/config/CxProperties.java#L338

### Expected Behavior

Trigger OSA scan with independent configuration as it is done for SCA and SAST

### Actual Behavior
Cannot trigger OSA scans because they are always disabled

**Comment by kmcdon83** [comment]
@miguelfreitas93 CxFlow supports SCA scanning, not Osa, and Osa will not be supported.  We do support Osa result processing (post scan integration with Jira for example).  The flag was set to false based on a POC implementation for OSA, which we wanted to revisit but it was instead switched to SCA only.

This is not a bug.

To enable SCA you need to specify the scanner in config as well as provide credentials.

```
cx-flow:
...
  enabled-vulnerability-scanners:
    - sca
    - sast
...

sca:
  appUrl: https://xxxxxxxx
  apiUrl: https://xxxxxxxx
  accessControlUrl: https://xxxxxxxxx
  tenant: <TENANT>
  username: XXXXXX
  password: XXXXXX
```
