### ISSUE TITLE
Allow all CxSCA configuration options in application.yml + Config as Code combo

### ISSUE THREAD

**Issue by brenwhyte** [checkmarx-ltd/cx-flow#688]
### Description

I'm trying to define CxSCA properties in `application.yml` along with developer supplied CxSCA properties in `cx.config`
Seems CxSCA properties in `application.yml` are ignored or not supported. (not supported I imagine)

### Expected Behavior
Right now I'd like for developers to "opt-in" to CxSCA usage.
My `application.yml` looks like:

```
*snip*
  enabled-vulnerability-scanners:
    - sast
#    - sca

...

sca:
  appUrl: https://sca.checkmarx.net
  apiUrl: https://api-sca.checkmarx.net
  accessControlUrl: https://platform.checkmarx.net
  tenant: 
  username: 
  password: 
  filter-severity:
    - high
#    - medium
#    - low

*snip
```

And opting-in a dev just needs to add the below to their `cx.config`:
```
{   "team": "/CxServer/Team/Squad",
    "additionalProperties": {
        "cxFlow": {
			"vulnerabilityScanners": ["sca", "sast"]
        }
}
```

That works are expected, the SCA properties for app, api, access control urls are used **but** all CxSCA scans end up with a Teamname of "All users"

Enter issue #634 
That now allowed for Devs to set their Team name via Config as Code, brilliant. 
eg:

```
{
	"team": "/CxServer/Team/Squad",
	"additionalProperties": {
		"cxFlow": {
			"vulnerabilityScanners": ["sca", "sast"]
		}
	},
	"sca": {
		"team": "/CxServer/Team/Squad"
	}
}
```

### Actual Behavior

It looks like the CxSCA settings above defined in application.yml (and also the Environment Variables like SCA_TENANT) are being ignored.
So if a user tries the above, we'll see this logged in the CxFlow logs:

```
2021-03-19 12:54:09.599 ERROR 1 --- [      flow-web1] c.checkmarx.flow.config.FlowAsyncConfig  : Error has occurred calling initiateAutomation. MachinaRuntimeException: sca scan failed.
Scan cannot be initiated. SCA application URL wasn't provided
```
The only way this now works is if developers specify all the CxConfig settings, eg

```
	"sca": {
		"appUrl": "https://sca.checkmarx.net",
		"apiUrl": "https://api-sca.checkmarx.net",
		"accessControlUrl": "https://platform.checkmarx.net",
		"tenant": "my-tenent",
		"team": "/CxServer/Team/Squad"
	}
``` 

Ideally I'd like to manage that for folks so all they need to worry about is say Team name, filter settings etc.

### Environment Details

GitLab SaaS
CxFlow 1.6.19
