### ISSUE TITLE
Define branches that can be targeted by PRs that don't update the issue tracker

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#726]
### Describe the problem

Customer request to define something like secondary protected branches.  PRs targeting the secondary branch perform a scan and issue PR comments, but a push to the secondary invokes a scan without an issue tracker update.  This is so they can push issues into the issue tracker only when pushing to a primary protected branch.

### Proposed solution

New config option like "branches" named "secondary-branches" that works the same way for PRs when PRs target secondary branches, but secondary branch push events don't update the issue tracker.

**Comment by cx-scord** [comment]
This structure could also be introduced inside the `branches` property of the `cx-flow` block with a property named `track-issues` or `track-bugs`, adding `name` to set the branch's name, like:

```yaml
cx-flow:
  branches:
    - name: main
      track-issues: true
    - name: development
      track-issues: false
```
