### ISSUE TITLE
Similarity-id not being added to fields that can be mapped in JIRA

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#774]
### Description

The `similarity-id` field result field is not being mapped on the JIRA configuration like it is in the CSV.

### Expected Behavior

Being able to map `similarity-id` field, to the report in JIRA similarly to other fields, like described here:
* https://github.com/checkmarx-ltd/cx-flow/blob/36984a917860002b8c3a706b425639f4a0bd1961/docs/Bug-Trackers-and-Feedback-Channels.md#-fields

### Actual Behavior

The `similarity-id` result field is not mapped in any required JIRA field to be mapped.

### Reproduction

YAML config for JIRA that should work, but doesn't output anything to JIRA :

```
jira:
  (...)
  fields:
    - type: result
       name: similarity-id
       jira-field-name: SimilarityID
       jira-field-type: label
```

### Environment Details

CxFlow 1.6.21

Code that maps the `similarity-id` for CSV and should exist the same way in JIRA:
* https://github.com/checkmarx-ltd/cx-flow/blob/60920be1b2764f71fad8dfa5a4940090e2a32c63/src/main/java/com/checkmarx/flow/custom/CsvIssueTracker.java#L186
