### ISSUE TITLE
Split 'New' vulnerabilities in PR comments from 'Recurrent' issues

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#797]
### Describe the problem

When receiving PR comments, the report returns all issues mingled together, new or recurrent ones, like the table below:

![image](https://user-images.githubusercontent.com/68207834/129253044-01a869d1-5506-40f2-80b5-b6248464052f.png)

### Proposed solution

To add a grouping configuration on each SCM block that would allow to either inform of only New issues or split them from the Recurrent ones.

Example for GitHub:
```yaml
github:
  (...)
  summary-group-issues: <together|split|new> ## Defaults to 'together'. 'split' creates 2 tables, one for new issues and another for recurrent ones, 'new' shows only the new issues.
```
It could look something like this or even a line for each individual vulnerability if that becomes possible in the future:

![image](https://user-images.githubusercontent.com/68207834/129254387-9d49092e-2d0d-432a-b1af-4a3e00d88d96.png)

### Additional details

This could (should?) be a config-as-code overridable configuration.
