### ISSUE TITLE
org.json.JSONException: JSONArray[0] not found.

### ISSUE THREAD

**Issue by cx-leonelsanches** [checkmarx-ltd/cx-flow#840]
### Description

> Trying to scan a project through a Webhook, I got the error.

### Expected Behavior

Project should scan normally.

### Actual Behavior

Scan simply fails

### Reproduction

- Using a GitHub repository, add a Webhook pointing to a running instance of CxFlow. 
- Use the files like below:

#### `application.yml`

```
server:
  port: 9095

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{15}){cyan}  [%clr(%X{cx}){blue}] %clr(:){faint} %replace(%m){'([\\|])','\\$1'}%n%wEx"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{15}){cyan}  [%clr(%X{cx}){blue}] %clr(:){faint} %replace(%m){'([\\|])','\\$1'}%n%wEx"
  file:
    name: cx-flow.log

cx-flow:
  # Agreed upon shared API token
  token: 12345
  bug-tracker: Csv
  bug-tracker-impl:
    - CxXml
    - Json
    - JIRA
    - GitLab
    - GitHub
    - Csv
    - Azure
    - Rally
  branches:
    - develop
    - master
    - security
  filter-severity:
    - High
  filter-category:
  filter-cwe:
  filter-status:
# track-application-only: false
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
#  break-build: true
#  wiki-url: https://custodela.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
#  codebash-url: https://cxa.codebashing.com/courses/
#  mail:
 #    host: smtp.gmail.com
 #    port: 587
 #    username: xxx
 #    password: xxx
 #    enabled:

checkmarx:
  version: 9.0
  username: your-username
  password: your-password
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: http://leonel-ws2016
  client-id: resource_owner_client
  scope: access_control_api sast_rest_api  
  # multi-tenant: true
  configuration: Default Configuration
  scan-preset: Checkmarx Default
  team: CxServer
  url: ${checkmarx.base-url}/cxrestapi
  #preserve-xml: true
  #incremental: true
#WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  #team-script:
  #project-script:

rally:
  token: xxxx
  rally-project-id: xxxx
  rally-workspace-id: xxxx
  url: https://rallydev.com
  api-url: https://rally1.rallydev.com/slm/webservice/v2.0

github:
  webhook-token: 12345
  token: xxxx
  url: https://github.com
  api-url: https://api.github.com/repos/
  false-positive-label: false-positive
  block-merge: false

gitlab:
  webhook-token: xxxx
  token: xxxx
  url: https://gitlab.com
  api-url: https://gitlab.com/api/v4/
  false-positive-label: false-positive
  block-merge: true

azure:
  webhook-token: xxxx
  token: xxxx
  url: https://dev.azure.com
  issue-type: issue
  api-version: 5.0
  false-positive-label: false-positive
  #block-merge: true

json:
  file-name-format: "[TEAM]-[PROJECT]-[TIME].json"
  data-folder: "/tmp/cxflow"

cx-xml:
  file-name-format: "[TEAM]-[PROJECT]-[TIME].xml"
  data-folder: "/tmp/cxflow"

csv:
  file-name-format: "[TEAM]-[PROJECT]-[TIME].csv"
  data-folder: "/tmp/cxflow"
  include-header: true
  fields:
    - header: Application
      name: application
      default-value: unknown
      #- header: Primary URL
      #name: static
      #default-value: ${tmp.url}
    - header: severity
      name: severity
    - header: Vulnerability ID
      name: summary
      prefix: "[APP]:"
    - header: file
      name: filename
    - header: Vulnerability ID
      name: summary
    - header: Vulnerability Name
      name: category
    - header: Category ID
      name: cwe
    - header: Description
      name: description
      #prefix: "*"
      #postfix: "*"
    - header: Severity
      name: severity
    - header: recommendation
      name: recommendation
    - header: Similarity ID
      name: similarity-id
```

#### `{your-repo-root}/.checkmarx/cx.config`

```
{
  "version": 1.0,
  "project": "BlackjackCSharp",
  "team": "/CxServer"
}
```

### Environment Details

- CxSAST 9.3 HF15 running in a Windows Server 2016 VM in AWS (EC2);
- In the same server, cx-flow 1.6.25 (Java 11) running as a server at port 9095;
- GitHub Webhook:

![image](https://user-images.githubusercontent.com/86265009/136291967-fdb1cf96-fe80-4664-a907-a27dcf8cd8b1.png)
