### ISSUE TITLE
Add optional Jira Api Token Authentication with Jira Data Server

### ISSUE THREAD

**Issue by wp-oa** [checkmarx-ltd/cx-flow#878]
### Describe the problem

> A clear description of what the problem is.

As it currently stands, in order for cx-flow to authenticate with Jira Data Center, a username and password must be provided. Using an Api Token results in a 401 Unauthorized error.

### Proposed solution

> A clear description of what you want to happen.

cx-flow should authenticate with Jira Data Center when provided a valid Jira api token.

### Additional details

> Add any other details / contexts / screenshots about the feature request.

Error is produced when invoking cx-flow through a GitLab pipeline
![image](https://user-images.githubusercontent.com/20896135/144909799-b6664dbc-b327-49fe-b77f-603eacfd8786.png)

Checkmarx Version: 9.2.0.41015
Jira Data Center Version: v8.19.0

**Comment by jbrotsos** [comment]
We only support username and token.

**Comment by wp-oa** [comment]
> We only support username and token.

Currently, an api token is not supported. What is refered to as `token` is actually just the password for the username. What I am suggesting is that support for using ONLY an api token for authentication is added.

**Comment by jbrotsos** [comment]
Hey @wp-oa ,

Where you seeing that we only use the password?

Thanks,
James

**Comment by wp-oa** [comment]
When invoking a cx-flow scan via GitLab pipeline, and providing the following environment variables, you get that 401 error.
```yaml
JIRA_URL: "<jira_data_center_url>"
JIRA_USERNAME: "checkmarx"
JIRA_TOKEN: $CHECKMARX_JIRA_TOKEN // This must be the jira users password. If you use an API token here it returns a 401. This is true in the absense of JIRA_USERNAME as well.
```

I can validate the token I was trying to use has the proper permissions to create an issue by using Postman and the create issue endpoint. Endpoint used: `https://<jira_data_center_url>/rest/api/2/issue/`
