### ISSUE TITLE
Map CxSCA scan results to JIRA fields

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#897]
### Describe the problem

CxFlow can trigger CxSCA scans and create JIRA tickets with predefined values but SCA results are currently unavailable to map on JIRA fields tickets like CxSAST's are on CxFlow configuration.
For example, we cannot mapping the `Violates Policy` field of SCA in a JIRA field.

### Proposed solution

Add a type of result like a sca-result to the JIRA and make all possible CxSCA field values available to map to JIRA fields, here's a possible example:

```yaml
jira:
   (...)
   fields:
     - type: sca-result
       name: violates-policy
       jira-field-name: "Policies Violation"
       jira-field-type: text
```
